spring.application.name=Todo
#server.port=6969
# anything you want to configure about application you can do it here.

spring.mvc.view.prefix = /WEB-INF/jsp/
spring.mvc.view.suffix = .jsp
# /src/main/resources/META-INF/resources  => spring already knows yaha tak ka path
# spring.mvc.view mention kia h too itna path to Spring ko pata hi h 

#logging.level.org.springframework = info
#logging.level.org.Project.Todo = debug

# set default date fromat : yyyy-MM-dd ; (m:minutes ; M:month)
spring.mvc.format.date = yyyy-MM-dd

# below 2 lines are to enable and set url for h2-database (In memory db of SpringBoot)
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:testdb

# below command is to run data.sql by default and that too only after executing Todo.java class i.e only after creating the table.
#spring.jpa.defer-datasource-initialization=true			

# below 5 lines are to connect with mysql container running on docker to spring
spring.datasource.url=jdbc:mysql://localhost:3306/todos
spring.datasource.username=todos-user
spring.datasource.password=dummytodos
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

#  MySQL  SQL > \connect todos-user@localhost:3306   - to connect your mysql shell (i.e terminal in my case ) to my database.
# > \use todos : to connect to your schema.
#docker run --detach
# --env MYSQL_ROOT_PASSWORD=dummypassword
# --env MYSQL_USER=todos-user 
# --env MYSQL_PASSWORD=dummytodos 
# --env MYSQL_DATABASE=todos 
# --name mysql 
# --publish 3306:3306 
# mysql:8-oracle


# below 2 command is to run data.sql by default and that too only after executing Todo.java class i.e only after creating the table. first one is for permission second is for timing.
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

logging.level.org.springframework.jdbc.datasource.init=DEBUG

