spring.application.name=restful-web-services
spring.mvc.format.date = yyyy-MM-dd

# sbi versioning -
spring.mvc.apiversion.use.path-segment=0

# your tomcat uses http based request but Talend api tester sends https request.

# below content is for initializing h2-console.
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.username=sa

# by default actuator show limited number of management options on `/actuator` so added the line below.
management.endpoints.web.exposure.include = * 

# for using data.sql
spring.jpa.defer-datasource-initialization=true

# set default date fromat : yyyy-MM-dd ; (m:minutes ; M:month)
spring.mvc.format.date = yyyy-MM-dd


# below content is for initializing my-sql.  ( host port dalna h url me)
spring.datasource.url = jdbc:mysql://localhost:3307/social-media-database
spring.datasource.username= social-media-user
spring.datasource.password= dummypassword
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect


# spring security - add one user here.
spring.security.user.name = prateek
spring.security.user.password = 123456