logging.level.org.springframework = debug
server.port = 5010
# this server.port is completely diffrent from what you mention in Dockerfile
# In docker file it is - ( container port of your DockerImage network).